# Generated by Django 4.2.20 on 2025-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0004_remove_account_is_admin_alter_coupon_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityverification",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
