# Generated by Django 4.2.20 on 2025-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0005_identityverification_status_vehicle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
