# Generated by Django 4.2.20 on 2025-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0006_advertiser_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("fixed amount", "Fixed Amount"),
                    ("percentage", "Percentage"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="triporder",
            name="actual_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("order", "reviewer")},
        ),
    ]
