# Generated by Django 4.2.20 on 2025-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0008_alter_triporder_actual_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triporder",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="triporder",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
