# Generated by Django 4.2.20 on 2025-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0009_alter_triporder_end_time_alter_triporder_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="total_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ride",
            name="available_seats",
            field=models.IntegerField(default=0),
        ),
    ]
